packages:
  - packages/*

catalogs:
  dev:
    "@eslint/js": ^9.18.0
    "@vitest/coverage-v8": ^3.0.2
    eslint: ^9.18.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-prettier: ^5.2.3
    eslint-plugin-react-hooks: ^5.1.0
    eslint-plugin-react-refresh: ^0.4.18
    glob: ^11.0.1
    globals: ^15.14.0
    happy-dom: ^16.6.0
    prettier: ^3.4.2
    tslib: ^2.8.1
    typescript: ^5.7.3
    typescript-eslint: ^8.21.0
    vitest: ^3.0.2
    zod: ^3.24.1
